2020-12-16 11:33:57,047 ERROR: Exception on /questionlist/0 [GET] [in D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py:1891] - [from 127.0.0.1 to http://127.0.0.1:5000/questionlist/0]
Traceback (most recent call last):
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Documenten\Projects\DataEnWatNu\src\blueprints\questions\routes.py", line 10, in question
    question = Question.get_by_id(1)
  File "D:\Documenten\Projects\DataEnWatNu\src\database.py", line 37, in get_by_id
    return cls.query().get(int(record_id))
  File "D:\Documenten\Projects\DataEnWatNu\src\database.py", line 80, in query
    return db.session.query(cls)
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\sqlalchemy\orm\scoping.py", line 163, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\sqlalchemy\orm\session.py", line 1585, in query
    return self._query_cls(entities, self, **kwargs)
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\sqlalchemy\orm\query.py", line 197, in __init__
    self._set_entities(entities)
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\sqlalchemy\orm\query.py", line 225, in _set_entities
    self._set_entity_selectables(self._entities)
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\sqlalchemy\orm\query.py", line 256, in _set_entity_selectables
    ent.setup_entity(*d[entity])
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\sqlalchemy\orm\query.py", line 4324, in setup_entity
    self._with_polymorphic = ext_info.with_polymorphic_mappers
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\sqlalchemy\util\langhelpers.py", line 884, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\sqlalchemy\orm\mapper.py", line 2155, in _with_polymorphic_mappers
    configure_mappers()
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\sqlalchemy\orm\mapper.py", line 3299, in configure_mappers
    mapper._post_configure_properties()
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\sqlalchemy\orm\mapper.py", line 1965, in _post_configure_properties
    prop.init()
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\sqlalchemy\orm\interfaces.py", line 197, in init
    self.do_init()
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\sqlalchemy\orm\relationships.py", line 2080, in do_init
    self._generate_backref()
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\sqlalchemy\orm\relationships.py", line 2329, in _generate_backref
    raise sa_exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Error creating backref 'case' on relationship 'Case.answer_case': property of that name exists on mapper 'mapped class Answer->Answer'
2020-12-16 11:46:12,465 ERROR: Exception on /questionlist/0 [GET] [in D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py:1891] - [from 127.0.0.1 to http://127.0.0.1:5000/questionlist/0]
Traceback (most recent call last):
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Documenten\Projects\DataEnWatNu\src\blueprints\questions\routes.py", line 12, in question
    form = QuestionType.query().get(Question.questiontype)  #OpenQuestionForm()
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\sqlalchemy\orm\query.py", line 1018, in get
    return self._get_impl(ident, loading.load_on_pk_identity)
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\sqlalchemy\orm\query.py", line 1135, in _get_impl
    return db_load_fn(self, primary_key_identity)
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\sqlalchemy\orm\loading.py", line 234, in load_on_pk_identity
    if None in primary_key_identity:
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\sqlalchemy\sql\elements.py", line 3275, in __bool__
    raise TypeError("Boolean value of this clause is not defined")
TypeError: Boolean value of this clause is not defined
2020-12-16 11:46:12,465 ERROR: Exception on /questionlist/0 [GET] [in D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py:1891] - [from 127.0.0.1 to http://127.0.0.1:5000/questionlist/0]
Traceback (most recent call last):
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Documenten\Projects\DataEnWatNu\src\blueprints\questions\routes.py", line 12, in question
    form = QuestionType.query().get(Question.questiontype)  #OpenQuestionForm()
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\sqlalchemy\orm\query.py", line 1018, in get
    return self._get_impl(ident, loading.load_on_pk_identity)
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\sqlalchemy\orm\query.py", line 1135, in _get_impl
    return db_load_fn(self, primary_key_identity)
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\sqlalchemy\orm\loading.py", line 234, in load_on_pk_identity
    if None in primary_key_identity:
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\sqlalchemy\sql\elements.py", line 3275, in __bool__
    raise TypeError("Boolean value of this clause is not defined")
TypeError: Boolean value of this clause is not defined
2020-12-16 11:47:11,173 ERROR: Exception on /questionlist/0 [GET] [in D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py:1891] - [from 127.0.0.1 to http://127.0.0.1:5000/questionlist/0]
Traceback (most recent call last):
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Documenten\Projects\DataEnWatNu\src\blueprints\questions\routes.py", line 12, in question
    form = QuestionType.query().get(Question.questiontype).form  #OpenQuestionForm()
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\sqlalchemy\orm\query.py", line 1018, in get
    return self._get_impl(ident, loading.load_on_pk_identity)
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\sqlalchemy\orm\query.py", line 1135, in _get_impl
    return db_load_fn(self, primary_key_identity)
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\sqlalchemy\orm\loading.py", line 234, in load_on_pk_identity
    if None in primary_key_identity:
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\sqlalchemy\sql\elements.py", line 3275, in __bool__
    raise TypeError("Boolean value of this clause is not defined")
TypeError: Boolean value of this clause is not defined
